application:
  host: "0.0.0.0"
  port: 8080
telegram:
  bot_token: "YOUR_TELEGRAM_API_TOKEN"
database:
  host: "localhost"
  port: 5432
  username: "example_user"
  password: "example_password"
  database_name: "example_db"
  require_ssl: false