name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres:14
        env:
          POSTGRES_USER: example_user
          POSTGRES_PASSWORD: example_password
          POSTGRES_DB: example_db
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      
